spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/techblog?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
    defer-datasource-initialization: true
    generate-ddl: true
  sql:
    init:
      mode: always

logging:
  level:
    org.hibernate.SQL: debug
    com.company.techblog: debug

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics